version: '3.3'
services:
  api:
    container_name: api
    restart: always
    build:
      context: api
    ports:
      - "3000:3000"
    environment:
        MONGO_URL: "mongodb://mongo:27017/companyManagementDemo"  
        API_PORT: 3000
    depends_on: 
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  ui:
    container_name: ui
    volumes: 
      - npm-cache:/root/.npm
    depends_on: 
      - api
    build:
      context: ui
    ports:
      - "4205:4205"
volumes:
  npm-cache:
    external: false   